name: Check on pull-request
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
    - name: Chckout pull request
      uses: actions/checkout@v2
    - name: Setup Bicep
      uses: anthony-c-martin/setup-bicep@v0.1
      with:
        version: v0.4.1272
    - name: Add problem matcher
      run: |
        echo "::add-matcher::.github/matcher/bicep-linter-warning.json"
        echo "::add-matcher::.github/matcher/bicep-linter-error.json"
    - name: Run Bicep build
      shell: bash
      run: |
        bash .github/commands/lint.bash
